Document: http-parser
Title: Debian http-parser Manual
Author: <insert document author here>
Abstract: This manual describes what http-parser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/http-parser/http-parser.sgml.gz

Format: postscript
Files: /usr/share/doc/http-parser/http-parser.ps.gz

Format: text
Files: /usr/share/doc/http-parser/http-parser.text.gz

Format: HTML
Index: /usr/share/doc/http-parser/html/index.html
Files: /usr/share/doc/http-parser/html/*.html
